[package]
name = "Bacchus-Serene"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
poise = "0.6.1"
tokio = { version = "1.40.0", features = ["rt-multi-thread"] }
http = "1.1.0"
rusqlite = "0.32.1"
r2d2 = "0.8.10"
r2d2_sqlite = "0.25.0"
dotenv = "0.15.0"
